API_KEY = 'MyGOmPOpp3pXqDSuntnWl1eDg'
API_KEY_SECRET = 'nkj8BMpyLvvVsWSUfb0MMTRMT0Zmwzvt7cRoY3WG0ykE5iCUaA'
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAAoxlQEAAAAAWXrMMAcs%2FyisEnerxW0gggmzieM' \
               '%3D9PErnz4fdmyFmd7PYRZDHuyFCNfNnCZuSRuK8Oib9lPXNTiOYX'
ACCESS_TOKEN = '800916529-247I4FMCD7pFDUW1RgjpE9RRyhH3HKpK5WWHSmjT'
ACCESS_SECRET_TOKEN = 'H1aCsKEezLBwjxkdafeEYgZtjR6KDTCzpxkTUkRKs5tDD'
